# Generated by Django 3.1.3 on 2020-11-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('task', models.TextField(verbose_name='Формулировка задачи')),
                ('isDone', models.BooleanField(default=False, null=True, verbose_name='Состояние задачи')),
            ],
        ),
    ]
